### ISSUE TITLE
[Refactor] Replace `requests` to `httpx`

### ISSUE THREAD

**Issue by lorddaedra** [getlago/lago-python-client#94]
Replace `requests` to `httpx`.

https://www.python-httpx.org/

Depends on: 
- #93, 
- #104

Is required for:
- #132

**Comment by akshatakulkarni25** [comment]
hey @lorddaedra can i contribute on this issue

**Comment by akshatakulkarni25** [comment]
okay thank you

**Comment by wintonzheng** [comment]
Any plan to add async/await support?

**Comment by vincent-pochet** [comment]
@wintonzheng It's not on our roadmap for now, but do not hesitate to contribute if you need such a support
